### ISSUE TITLE
Generates a duplicate tailwind config file

### ISSUE THREAD

**Issue by Oni-giri** [tremorlabs/tremor-cli#8]
Hello,

I'm working on a Typescript project with a `tailwing.config.ts` file. I used the cli to set up Tremor, and it created a `tailwind.config.js` file along the existing .ts file. Maybe the cli tool should check if the project is in TS or JS, and if a config.ts file already exists?

**Comment by rajdip-b** [comment]
Hello, I have created a [PR](https://github.com/tremorlabs/tremor-cli/pull/9) addressing the same. Feedback would be helpful!
